OWNERS
OWNERS_ALIASES

This patch updates OWNERS and OWNERS_ALIASES files by just copying
from networking repo https://github.com/knative/networking.
Please also refer to https://github.com/knative/community/issues/389.
/cc @tcnghia @ZhiminXiang

Update OWNERS and OWNERS_ALIASES by copying from networking repo

---

test/conformance/ingressv2/headers.go
test/conformance/ingressv2/run.go

This patch adds header tests such as `TestPreSplitSetHeaders`,
`TestPostSplitSetHeaders` and `TestTagHeaders`.
They are same test with https://github.com/knative/networking/blob/main/test/conformance/ingress/headers.go 
but uses Ingress v2 resources.
Note only `TestProbeHeaders` is not included in this PR as prober is KIngress specific, is not in Ingress v2.

Add Header tests

---

test/conformance/ingressv2/util.go
test/conformance/ingressv2/util_test.go

This patch enables `IsHTTPRouteReady()` function to verify HTTPRoute status.
Istio and Contour both support the status now.
/cc @markusthoemmes @tcnghia @ZhiminXiang 
Fix https://github.com/knative-sandbox/net-ingressv2/issues/30

Add IsHTTPRouteReady status check

---

test/conformance/ingressv2/run.go

This patch adds TestPercentage to contour test.
Contour implemented it a few days ago by https://github.com/projectcontour/contour/commit/b155ccc1da240c08ceabd2824b40793cb8a705bf
/cc @markusthoemmes @tcnghia @ZhiminXiang

Add TestPercentage to contour

---

.github/workflows/kind-e2e.yaml

kind-e2e waits pods to be up by `kubectl wait pod
--for=condition=Ready -n "contour-operator"` but it gets error when
any pods are not created yet in the namespace.
The script is failing sometimes due to the issue:
e.g. https://github.com/knative-sandbox/net-ingressv2/runs/2418620924?check_suite_focus=true
Hence, This patch changes it to wait Deployment to be Available.
/cc @markusthoemmes @tcnghia @ZhiminXiang

Wait for contour-operator deployment instead of pod

---

.github/workflows/kind-e2e.yaml
test/conformance/ingressv2/run.go
test/conformance/ingressv2/util.go
test/conformance/ingressv2/visibility.go
third_party/contour-head/gateway/gateway-internal.yaml

This patch adds `TestVisibility` in Contour tests.
`visibility/split` and `visibility/path` are not executed yet as these are flake now.
/cc @markusthoemmes @tcnghia @ZhiminXiang

Add TestVisibility in Contour

---

DEVELOPMENT.md
test/conformance/ingressv2/basic.go
test/conformance/ingressv2/grpc.go
test/conformance/ingressv2/headers.go
test/conformance/ingressv2/hosts.go
test/conformance/ingressv2/path.go
test/conformance/ingressv2/percentage.go
test/conformance/ingressv2/rewrite.go
test/conformance/ingressv2/rule.go
test/conformance/ingressv2/timeout.go
test/conformance/ingressv2/util.go
test/conformance/ingressv2/visibility.go
test/conformance/ingressv2/websocket.go

This patch adds a new function `portNumPtr()` to get port pointer.
/kind cleanup

Use common function to get port pointer

---

.github/workflows/kind-e2e.yaml
test/conformance/ingressv2/run.go
test/conformance/ingressv2/util.go
test/conformance/ingressv2/visibility.go
third_party/contour-head/gateway/gateway-external.yaml
third_party/contour-head/gateway/gateway-internal.yaml
third_party/istio-head/gateway/203-local-gateway.yaml
third_party/istio-head/gateway/300-gateway-local.yaml

This patch adds visbility test for istio.
Also, it changes HTTPRoute's Gateway selector to `GatewayAllowAll`
from `GatewayAllowFromList`. (So https://github.com/knative-sandbox/net-ingressv2/pull/47 is also covered eventually.)
/cc @ZhiminXiang @markusthoemmes @howardjohn

Add visibility test for Istio

---

go.mod
go.sum
test/clients.go
test/util.go
vendor/knative.dev/pkg/test/e2e_flags.go
vendor/knative.dev/pkg/test/request.go
vendor/modules.txt

This patch is same with https://github.com/knative/networking/commit/bf0fc8442924badb4fb87572d23f5025887a1925.
The client usage needs to be updated otherwise it starts failing as https://github.com/knative-sandbox/net-ingressv2/pull/101.
/cc @dprotaso @ZhiminXiang

Update the use of Client

---

test/conformance/ingressv2/percentage.go
test/conformance/ingressv2/visibility.go

Istio had an issue for weight 0 handling as https://github.com/istio/istio/issues/31745
but it was fixed now.
This patch drops the workaround.
/cc @ZhiminXiang

Remove workaround of weight 0 test for Istio

---

third_party/contour-head/gateway/gateway-external.yaml
third_party/contour-head/gateway/gateway-internal.yaml

As contour-operator updated the spec by
https://github.com/projectcontour/contour-operator/commit/d094fc6b4202eadf78f58f1a137fc0c34952f113
this patch updates the configurations in this repo.
It should pass tests with contour now.
/cc @markusthoemmes @ZhiminXiang

Update contour configurations

---

.github/workflows/kind-e2e.yaml
CONTRIBUTING.md
DEVELOPMENT.md
README.md
go.mod
test/conformance/ingressv2/basic.go
test/conformance/ingressv2/grpc.go
test/conformance/ingressv2/headers.go
test/conformance/ingressv2/hosts.go
test/conformance/ingressv2/path.go
test/conformance/ingressv2/percentage.go
test/conformance/ingressv2/rewrite.go
test/conformance/ingressv2/rule.go
test/conformance/ingressv2/timeout.go
test/conformance/ingressv2/util.go
test/conformance/ingressv2/visibility.go
test/conformance/ingressv2/websocket.go
test/upload-test-images.sh
third_party/contour-head/gateway/gateway-external.yaml
third_party/contour-head/gateway/gateway-internal.yaml
third_party/istio-head/gateway/300-gateway-local.yaml
third_party/istio-head/gateway/300-gateway.yaml

As repo name was updated, this patch replaces all `net-ingressv2` with `net-gateway-api`.

Replace net-ingressv2 with net-gateway-api

---

pkg/reconciler/ingress/config/gateway.go
pkg/reconciler/ingress/config/gateway_test.go

Currently configmap fails to `yaml.Unmarshal` due to non-string value.
So this patch uses `visibilityValue` struct to parse the config-gateway.
Fix https://github.com/knative-sandbox/net-gateway-api/issues/171

Fix to parse `NamespacedName` in config-gateway

---

pkg/reconciler/ingress/ingress_test.go
pkg/reconciler/ingress/lister.go
pkg/reconciler/ingress/lister_test.go
third_party/contour-head/gateway/gateway-internal.yaml

Currently prober code probes public (`hello.example.com`) and private (`hello.default.svc.cluster.local`) services by ingress's private endpoint IP only. 
i.e.
- `-H "hello.example.com"` `<private ingress's IP>`
- `-H "hello.default.svc.cluster.local"` `<private ingress's IP>`
This probe code works with Istio and Kourier as they map two services (local and external) to one deployment.
However, it does not work with Contour as it maps one service to one deployment.
So, this patch fixes the prober code to use each public and private IPs for external and local service.
i.e.
- `-H "hello.example.com"` `<public inigress's IP>`
- `-H "hello.default.svc.cluster.local"` `<private inigress's IP>`
Part of https://github.com/knative-sandbox/net-gateway-api/pull/179

Use each IP to probe public and private services

---

test/conformance/ingressv2/visibility.go
test/kind-conformance-contour.sh
test/kind-conformance-istio.sh

Currently `TestVisibilitySplit` is flaky so drop `t.Parallel()` until
issues/185 was solved.
This patch also remove some unsupported test from contour.

Drop t.Parallel() in TestVisibilitySplit until issues/185 was fixed

---

config/controller.yaml
hack/release.sh

This patch adds `hack/release.sh` with clean up of `controller.yaml`.

Add hack/release.sh

---

README.md

This patch adds Getting started guide to run net-gateway-api with Knative.
Also, it includes https://github.com/knative-sandbox/net-gateway-api/pull/168.

Add getting started in README

---

README.md
test/e2e-common.sh
test/e2e-tests.sh
test/ha/controller_test.go
test/ha/ha.go
test/kind-e2e-contour.sh
test/kind-e2e-istio.sh
vendor/knative.dev/pkg/test/ha/ha.go
vendor/modules.txt

This patch adds HA test for net-gateway-api controller.
The logic is same with Kourier's HA test.

Add HA test for net-gateway-api controller

---

docs/test-version.md
hack/test-env.sh

This patch bumps Istio and Contour tested versions to the 1.11.5 and 1.19.1 before the release.

Bump istio and Contour to the 1.11.5 and 1.19.1

---

hack/update-codegen.sh

As current script generates the Gateway API CRD by `kubectl kustomize`,
it fails when kubectl does not exist.
E.g. "Update Deps and Codegen" in knative-sandbox/knobots misses the command as
https://github.com/knative-sandbox/knobots/runs/4408339616?check_suite_focus=true
So this patch changes to generate the CRD only when `kubectl` command exists.

Generate Gateway API CRD only when kubectl exists

---

.github/workflows/kind-conformance.yaml
.github/workflows/kind-e2e.yaml

As k8s min version was bumped to 1.21 by knative/pkg#2397, this patch bumps k8s version in kind.

Bump k8s version to 1.23.0 in kind

---

config/100-gateway-api.yaml
docs/test-version.md
hack/test-env.sh

This patch bumps:
- Gateway API version to v0.4.2.
- Istio to v1.13.2
- Contour to v1.20.1

Bump Gateway API version to v0.4.2

---

.github/workflows/kind-conformance.yaml
.github/workflows/kind-e2e.yaml

As per title, this patch bumps k8s version in KinD.

Bump k8s version in KinD

---

.github/workflows/kind-conformance.yaml
.github/workflows/kind-e2e.yaml

This patch bumps kind version 0.12.0 for k8s 1.23.
Since an issue https://github.com/knative/networking/issues/660 exists before,
we didn't update the version but it could be fixed by
dropping `apiVersion: kubeadm.k8s.io/v1beta2` from `kubeadmConfigPatches`.

Bump kind version to 0.12.0 for k8s 1.23

---

config/100-gateway-api.yaml
docs/test-version.md
hack/test-env.sh

This patch bumps tested contour version to 1.21.0.
gateway-api also bumps but it just includes minor change as per https://github.com/kubernetes-sigs/gateway-api/releases/tag/v0.4.3.

Bump Contour version to v1.21.0

---

.github/workflows/kind-conformance.yaml
.github/workflows/kind-e2e.yaml

Signed-off-by: Paul S. Schweigert <paulschw@us.ibm.com>
Since we will probably be supporting Kubernetes v1.24 in the next release, and kind v0.13.0+ is required to run Kubernetes v1.24.0+ images, let's go ahead and bump the versions now, so we have a chance to work out any issues before the next release.

bump kind and k8s versions in kind-e2e tests

---

docs/test-version.md
hack/test-env.sh

Use a recent commit of Contour in order to use the update to Gateway API v0.5.0-rc1.
Partially addresses: https://github.com/knative-sandbox/net-gateway-api/issues/308.

Bump Contour to a recent commit

---

docs/test-version.md
hack/test-env.sh

In Draft, depends on https://github.com/knative-sandbox/net-gateway-api/pull/329?w=1.

Bump Istio to v1.14.1

---

.github/workflows/kind-conformance.yaml
.github/workflows/kind-e2e.yaml

Same fix with https://github.com/knative-sandbox/net-kourier/pull/881.

Bump Go version to 1.18 for CI

---

go.mod
go.sum
test/conformance/gateway-api/path.go
test/conformance/gateway-api/percentage.go
test/conformance/gateway-api/visibility.go
vendor/golang.org/x/sync/AUTHORS
vendor/golang.org/x/sync/CONTRIBUTORS
vendor/golang.org/x/sync/errgroup/errgroup.go
vendor/modules.txt

https://github.com/knative/pkg/issues/2556
cc @dprotaso

Stop using knative.dev/pkg/pool, use errgroup instead

---

.github/ISSUE_TEMPLATE/conformance-tests-checklist.yaml

Add a checklist for tracking conformance tests succeed for each implementation

---

pkg/reconciler/ingress/controller.go
pkg/reconciler/ingress/controller_test.go
pkg/reconciler/ingress/ingress.go
pkg/reconciler/ingress/ingress_test.go
pkg/reconciler/ingress/reconcile_resources.go
pkg/reconciler/ingress/resources/helpers.go
pkg/reconciler/ingress/resources/httproute.go
pkg/reconciler/ingress/resources/httproute_test.go
pkg/reconciler/ingress/resources/reference_grant.go
pkg/reconciler/testing/listers.go
test/clients.go
test/conformance/gateway-api/basic.go
test/conformance/gateway-api/grpc.go
test/conformance/gateway-api/headers.go
test/conformance/gateway-api/hosts.go
test/conformance/gateway-api/path.go
test/conformance/gateway-api/percentage.go
test/conformance/gateway-api/rule.go
test/conformance/gateway-api/timeout.go
test/conformance/gateway-api/util.go
test/conformance/gateway-api/util_test.go
test/conformance/gateway-api/visibility.go
test/conformance/gateway-api/websocket.go

- Use ReferenceGrant instead of ReferencePolicy
- When v0.6.0 comes out we can drop v1alpha2.ReferenceGrant

Use v1beta1 APIs

---

.github/workflows/kind-e2e.yaml
config/100-gateway-api.yaml
docs/test-version.md
hack/test-env.sh

As per tittle, this patch bumps Gateway API version to v0.6.0.
/cc @dprotaso @ReToCode

Bump Gateway API testing version to v0.6.0

---

third_party/contour/gateway-external.yaml
third_party/contour/gateway-internal.yaml
third_party/istio/300-gateway.yaml
third_party/istio/300-gatewayclass.yaml

This is a tiny change which bumps v1beta1 Gateway in `third_party` directory.
It started producing the following warning message:
```
$ kubectl apply -f ./third_party/istio
service/knative-local-gateway created
Warning: The v1alpha2 version of Gateway has been deprecated and will be removed in a future release of the API. Please upgrade to v1beta1.
gateway.gateway.networking.k8s.io/knative-local-gateway created
gateway.gateway.networking.k8s.io/knative-gateway created
Warning: The v1alpha2 version of GatewayClass has been deprecated and will be removed in a future release of the API. Please upgrade to v1beta1.
Warning: resource gatewayclasses/istio is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be …
```

Use v1beta1 Gateway

---

docs/test-version.md
hack/test-env.sh

As per title, this patch bumps Istio version to 1.7.0 for test.

Bump Istio version to 1.7.0

---

.github/dependabot.yml

The automatic PR https://github.com/knative-sandbox/net-gateway-api/pull/503 (bump to 0.7.2) worked fine this time, but we need to bump manual change like https://github.com/knative-sandbox/net-gateway-api/pull/494.
So this patch adds `sigs.k8s.io/gateway-api ` to ignore list.

Do not bump sigs.k8s.io/gateway-api via dependabot

---

config/controller.yaml

- related to https://github.com/knative-extensions/net-certmanager/pull/584
-
-
/kind <kind>
Fixes #
```release-note
Controller and webhooks now have a seccompProfile.type set to RuntimeDefault
```
**Docs**
```docs
```

add seccompProfile to controller security context

---

docs/test-version.md
hack/test-env.sh

This patch mumps istio tested version to 1.19.3 which fixes the security vulnerabilities.

Bump Istio to 1.19.3

---

test/e2e-common.sh

As per title, this patch adds to wait `deploy/gateway-api-admission-server` until it becomes Ready.
Ideally, we want to verify `validatingwebhookconfigurations.admissionregistration.k8s.io` but it does not have the status so we wait for deployment (pod) becomes Ready.
/kind cleanup
```release-note
NONE
```
Fix https://github.com/knative-extensions/net-gateway-api/issues/570

Wait for deploy/gateway-api-admission-server to make sure webhook is ready

---

.github/workflows/kind-e2e.yaml

- Drop testing on k8s v1.26
Fixes #588
/assign @dprotaso 
/assign @nak3

Drop testing on k8s v1.26

---

.github/workflows/kind-e2e.yaml

- drop k8s 1.27 from kind testing
- add k8s v1.29 to kind testing
PS: Bump of client libraries will happen in https://github.com/knative/pkg/issues/2958

drop k8s 1.27 from kind testing and add v1.29

---

docs/test-version.md
hack/test-env.sh

- bump Contour version to 1.28.1
Fixes #622

Bump Contour to v1.28.1

---

.github/workflows/kind-e2e.yaml

It now uses the reusable action
/assign @izabelacg

bump golang to v1.22

---

docs/test-version.md
hack/test-env.sh

Istio update test is very flakey - part of https://github.com/knative-extensions/net-gateway-api/issues/18

disable update test for istio

---

pkg/reconciler/ingress/fixtures_test.go
pkg/reconciler/ingress/ingress.go
pkg/reconciler/ingress/ingress_test.go
pkg/reconciler/ingress/lister_test.go
pkg/reconciler/ingress/reconcile_resources.go

Serving uses multiple visibilities in it's KIngress which triggered a problem in the three phase probing.
This issue fixes that problem and adds the serving specific test cases
Fixes: https://github.com/knative-extensions/net-gateway-api/issues/18
Unblocks - https://github.com/knative/serving/pull/15136

Fix probing when KIngress has multiple visibilities (External/ClusterLocal)

---

pkg/reconciler/ingress/ingress.go
pkg/reconciler/ingress/ingress_test.go
pkg/reconciler/ingress/reconcile_resources.go
pkg/reconciler/ingress/resources/httproute.go
pkg/status/status.go
pkg/status/status_test.go

Prior we would try to ensure all the child HTTPRoute's had the same probe hash.
This would allow us to do a single query to the status prober for
readiness.
This didn't work well practice and we would end up in scenarios were
the child routes were in different stages of the three phases of
probing.
Instead we now have a probe entry per HTTPRoute and the callback key to
trigger reconciliation is the Ingress's key.
We now also perform probing only when the HTTPRoute is Accepted

Status probing is now tied to the HTTPRoute

---

pkg/reconciler/ingress/reconcile_resources.go
pkg/reconciler/ingress/resources/helpers.go

We only need to probe just one since we want to validate a
single backend is reachable.
Now we choose only the longest cluster local host

Don't probe all the cluster local hosts 

---

pkg/reconciler/ingress/ingress_test.go
pkg/reconciler/ingress/reconcile_resources.go

A stale httproute in the informer cache can result in probing to get stuck.
This would cause the reconciler to detect a new backend and revert from
our 'transitioning' phase back to the endpoint phase.
The changes tweaks the state machine so that we only consider 'new'
backends if the ingress hash has changed.

Fix probing getting stuck forever

---

test/clients.go
third_party/contour/gateway-external.yaml
third_party/contour/gateway-internal.yaml
third_party/istio/300-gateway-local.yaml
third_party/istio/300-gateway.yaml

- replace v1beta1 apis with v1 in yaml files
- 
Relates to #687

replace v1beta1 apis with v1 in yaml files

---

README.md

With the latest improvements to net-gateway-api and solidification of the config format (to match what we did in net-istio) 
I think we're good to mark this integration as beta so we get some more usage.

Promote Maturity Status to Beta

---

pkg/reconciler/ingress/ingress.go
pkg/reconciler/ingress/ingress_test.go
pkg/reconciler/ingress/lister.go
pkg/reconciler/ingress/lister_test.go
test/e2e-common.sh
test/e2e/gateway_config_test.go

* addressing PR comments from #685
- :broom: clean up stuff based on @dprotaso 's comments on #685 
/kind cleanup
Fixes #665 
```release-note
N/A
```
**Docs**
```docs
N/A
```

followup changes from #685

---

pkg/reconciler/ingress/ingress.go

- :broom: use `errors.Is()`
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

followup from #703: check error type properly

---

docs/test-version.md
hack/test-env.sh

- :broom: Bump Istio to version 1.22.0
- :broom: Bump Contour to version 1.29.0
/kind enhancement
```release-note
Testing with Contour v1.29.0 and Istio v1.22.0
```

Bump Istio and Contour version

---

.github/workflows/kind-e2e.yaml
hack/test-env.sh
test/e2e-common.sh
test/e2e/gateway_config_test.go
test/e2e/testdata/envoy-gateway-no-service-vis.yaml
third_party/envoy-gateway/config-gateway.yaml
third_party/envoy-gateway/config_test.go
third_party/envoy-gateway/external.yaml
third_party/envoy-gateway/internal.yaml
third_party/istio/300-gateway.yaml

Part of https://github.com/knative-extensions/net-gateway-api/issues/566

 Add envoy gateway testing

---

.github/workflows/knative-dependabot.yaml

- Use shared go set-up action
- Indirectly bump to golang 1.22
- Should fix https://github.com/knative-extensions/net-gateway-api/actions/runs/10280449982/job/28447822704
/assign @dprotaso 
/assign @dsimansk

Use shared go set-up action

---

.github/workflows/kind-e2e.yaml
docs/.test-version.template
docs/test-version.md
hack/test-env.sh
test/e2e-tests.sh
third_party/gateway-api/gateway-api.yaml

Bump Kind and k8s version
