knative-extensions/net-gateway-api

test/conformance/ingressv2/path.go, test/conformance/ingressv2/percentage.go, test/conformance/ingressv2/rule.go, test/conformance/ingressv2/run.go
This patch adds `dispatch/*` tests.
=> Add dispatch tests

test/conformance/ingressv2/basic.go, test/conformance/ingressv2/headers.go, test/conformance/ingressv2/hosts.go, test/conformance/ingressv2/path.go, test/conformance/ingressv2/percentage.go, test/conformance/ingressv2/rule.go, test/conformance/ingressv2/run.go, test/conformance/ingressv2/timeout.go, test/conformance/ingressv2/util.go
This patch adds TestMultipleHosts and TestTimeout.
=> Add TestMultipleHosts and TestTimeout

test/conformance/ingressv2/run.go, test/conformance/ingressv2/util.go, test/conformance/ingressv2/websocket.go
This patch adds WebSocket tests for ingress v2.
=> Add websocket tests

test/conformance/ingressv2/grpc.go, test/conformance/ingressv2/run.go, test/conformance/ingressv2/timeout.go, test/conformance/ingressv2/util.go, test/conformance/ingressv2/websocket.go
=> Add gRPC test

.github/workflows/kind-e2e.yaml
This patch changes to use random cluster suffix.
Istio fixed the issue by https://github.com/istio/istio/issues/29250
Also it enables Slack notification when scheduled job failed.
=> Use random cluster suffix

test/conformance/ingressv2/rewrite.go, test/conformance/ingressv2/run.go, test/conformance/ingressv2/util.go
This patch adds TestRewriteHost.
https://github.com/istio/istio/pull/31852 fixed a header operation
issue so we can support it now.
=> Add TestRewriteHost

test/conformance/ingressv2/rule.go
This is a same enhancement with https://github.com/knative/networking/pull/385.
`TestRule` creates two rules to confirm each rule work fine.
But we are not sure if test requests hit the correct backend - `fooName`
svc or `barName` svc by current code.
Hence this patch appends header to verify we hit expected backend
/kind enhancement
```release-note
NONE
```
=> Append headers to TestRule to verify we hit expected backend

test/conformance/ingressv2/run.go
Since this broker issue https://github.com/projectcontour/contour/issues/3591
was solved, we can run multiple tests now.
/cc @markusthoemmes @tcnghia @ZhiminXiang
=> Add contour tests

test/clients.go, test/conformance/ingressv2/util.go
Not sure how these slipped.
/assign @nak3
=> Fix revive related linting issues

.github/workflows/kind-e2e.yaml
This just spams the slack channel every few hours
=> drop e2e scheduled runs to once a day

test/conformance/ingressv2/headers.go, test/conformance/ingressv2/path.go, test/conformance/ingressv2/timeout.go
This is the same fix with https://github.com/knative/networking/pull/467
but against net-ingressv2.
=> Fix the Go iterator capture issue

pkg/reconciler/ingress/ingress_test.go
This patch adds unit test for ingress reconciler.
It adds the first reconciler for Ingress with prober success, fails, error.
It still needs more scenario e.g. invalid ingress, delete ingress etc but will send in another PR.
=> Add unit test for reconciler

hack/tools.go, test/config/chaosduck.yaml, test/config/leader-election.yaml, vendor/knative.dev/pkg/kflag/doc.go, vendor/knative.dev/pkg/kflag/set.go, vendor/knative.dev/pkg/leaderelection/chaosduck/main.go, vendor/modules.txt
This patch adds chaos duck for make test more strict.
=> Add chaos duck for controller

test/config/200-service-account.yaml, third_party/istio/gateway/203-local-gateway.yaml
Just some more instances - the third party gateway one is being pulled into serving
=> drop serving release label

config/controller.yaml
This patch fixes https://github.com/knative-sandbox/net-gateway-api/issues/271
Fix https://github.com/knative-sandbox/net-gateway-api/issues/271
/cc @carlisia @ZhiminXiang @dprotaso
=> Fix wrong labelSelector in podAntiAffinity

pkg/reconciler/ingress/config/store.go, pkg/reconciler/ingress/controller.go, pkg/reconciler/ingress/controller_test.go, pkg/reconciler/ingress/ingress_test.go, pkg/reconciler/ingress/resources/httproute.go, test/conformance/ingressv2/headers.go
Signed-off-by: Paul S. Schweigert <paulschw@us.ibm.com>
Fixes deprecations from `networking/pkg` refactor : https://github.com/knative/networking/pull/670
=> Updates for deprecated network dependencies

pkg/reconciler/ingress/lister.go, pkg/reconciler/ingress/lister_test.go, test/kind-e2e-istio.sh
- :bug: Use ports from Endpoints when probing, rather than fixed constant
/kind bug
/kind cleanup
```release-note
Gateway-api now probes the first port in the gateway-service's endpoints, rather than fixed ports.
```
**Docs**
```docs
Not needed at this time
```
=> Fix probes for internal addresses when using one contour

docs/.test-version.template, docs/test-version.md, hack/test-env.sh, test/e2e-tests.sh, test/kind-conformance-contour.sh, test/kind-conformance-istio.sh, test/kind-e2e-contour.sh, test/kind-e2e-istio.sh
Related: [TestVisibilitySplit with istio is not stable · Issue #185 · knative-sandbox/net-gateway-api](https://github.com/knative-sandbox/net-gateway-api/issues/185).
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
/assign @nak3
=> Skip Istio TestVisibilitySplit failing test for now

config/100-gateway-api.yaml, docs/test-version.md, go.mod, go.sum, hack/test-env.sh, vendor/modules.txt, vendor/sigs.k8s.io/gateway-api/apis/v1alpha2/gateway_types.go, vendor/sigs.k8s.io/gateway-api/apis/v1alpha2/httproute_types.go, vendor/sigs.k8s.io/gateway-api/apis/v1alpha2/object_reference_types.go, vendor/sigs.k8s.io/gateway-api/apis/v1alpha2/referencegrant_types.go, vendor/sigs.k8s.io/gateway-api/apis/v1alpha2/shared_types.go, vendor/sigs.k8s.io/gateway-api/apis/v1alpha2/tcproute_types.go, vendor/sigs.k8s.io/gateway-api/apis/v1alpha2/tlsroute_types.go, vendor/sigs.k8s.io/gateway-api/apis/v1beta1/httproute_types.go, vendor/sigs.k8s.io/gateway-api/apis/v1beta1/shared_types.go
=> ⬆️  Bump Gatewy API version to v0.5.0

docs/test-version.md, hack/test-env.sh
=> bump istio to v1.14.3

.github/ISSUE_TEMPLATE/conformance-tests-checklist.yaml
=> Improve conformance test checklist label/description

.github/ISSUE_TEMPLATE/kingress-tests-checklist.yaml
Closes https://github.com/knative-sandbox/net-gateway-api/issues/355.
=> Add checklist for kingress conformance tests

config/100-gateway-api.yaml, docs/test-version.md, hack/test-env.sh
=> bump istio to 1.16.0

go.mod, pkg/client/gatewayapi/clientset/versioned/fake/register.go, pkg/client/gatewayapi/clientset/versioned/scheme/register.go, pkg/reconciler/ingress/resources/helpers.go, test/conformance/gateway-api/util.go
See: https://github.com/knative/serving/issues/13747
=> [release-1.8] trigger to build release with go1.19.6

.github/workflows/kind-e2e.yaml
- Updated version in kind-e2e.yaml
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Bump Kind Version

config/100-gateway-api.yaml, docs/test-version.md, hack/test-env.sh
This patch bumps Gateawy API, Istio and Contour version.
=> Bump Gateawy API, Istio and Contour version

.github/dependabot.yml, .github/workflows/knative-dependabot.yaml
This patch adds dependabot and auto update deps as discussed in https://github.com/knative/pkg/issues/2759.
=> Add dependabot and auto update deps

docs/test-version.md, hack/test-env.sh, pkg/reconciler/ingress/resources/httproute.go, pkg/reconciler/ingress/resources/httproute_test.go
- Propagate `HostRewrite` from Knative Ingress to `HttpRoute`
/kind enhancement
Fixes #533
=> Propagate HostRewrite from Knative Ingress to HttpRoute

README.md
/kind documentation
removed duplicated section from docs
=> removed duplicated section from docs

hack/release.sh
- 🧹 Add gateway api crds file to release
/kind cleanup
Fixes #539
=> Add gateway api crds file to release

docs/test-version.md, hack/test-env.sh, test/e2e-common.sh, third_party/gateway-api/gateway-api.yaml
=> bump istio to 1.20.3 and gateway api to v1

pkg/reconciler/ingress/lister.go
- add the port name used by contour so lister can match on and find the correct port
/kind :bug: 
Fixes #639
=> add the port name used by contour in lister matching

docs/test-version.md, hack/test-env.sh
* bump Contour version to 1.28.2
=> Bump contour to 1.28.2

docs/test-version.md, hack/test-env.sh
new version of contour came out a few hours ago ;)
I bumped Istio as well
/assign @izabelacg
=> bump contour and istio

pkg/reconciler/ingress/ingress_test.go
Merging TestReconcileProberNotReady into TestReconcileProbing
/assign @izabelacg 
Pulling these commits from [#672](https://github.com/knative-extensions/net-gateway-api/pull/672)
=> refactor some probing tests

pkg/status/status.go
Missed in https://github.com/knative-extensions/net-gateway-api/pull/679
/assign @izabelacg
=> fix interface to match prober

test/e2e-common.sh, third_party/contour/config-gateway.yaml, third_party/contour/gateway-external.yaml, third_party/contour/gateway-internal.yaml
- **rename some contour resources to be more succinct**
- **update name**
=> simplify contour naming

.golangci.yaml
/assign @skonto 
/assign @dsimansk
=> fix linter config

pkg/reconciler/ingress/ingress_test.go, pkg/reconciler/ingress/resources/reference_grant.go, pkg/reconciler/ingress/resources/reference_grant_test.go
Fixes https://github.com/knative-extensions/net-gateway-api/issues/779 and https://github.com/knative-extensions/net-gateway-api/issues/827
Signed-off-by: Rajat Vig <rvig@etsy.com>
=> Create a per ingress ReferenceGrant to avoid conflicts in the same namespace
